dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.2
  - smartcontractkit/chainlink-brownie-contracts@0.6.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.2'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.6.1'
    version: 0.8.13
    viaIR: True
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  sepolia2:
    link: "0x779877A7B0D9E8603169DdbD7836e478b4624789"
    vrf_coordinator: "0x8103B0A8A00be2DDC778e6e7eaa21791Cd364625"
    key_hash: "0x474e34a077df58807dbe9c96d3c009b23b3c6d0cce433e59bbf5b34f823bc56c"


